name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - main # Or your primary branch name
    paths:
      - 'demo/**' # Only run if demo files change
      - '.github/workflows/deploy-demo.yml' # Or the name of this workflow file
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy Demo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: ./demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # working-directory is not applicable to uses steps directly like this
        # checkout action checks out to the GITHUB_WORKSPACE root

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a version compatible with your project
          # Caching disabled for diagnostics

      - name: Install root dependencies
        run: npm ci
        working-directory: . # Run this at the repository root

      - name: Clean demo node_modules
        run: rm -rf demo/node_modules
        # This runs from the GITHUB_WORKSPACE root

      - name: Clear npm cache
        run: npm cache clean --force
        # This runs from the GITHUB_WORKSPACE root, affecting the global npm cache for the runner

      - name: Install demo dependencies
        working-directory: ./demo
        run: |
          npm install --ignore-scripts
          npm rebuild esbuild --force

      - name: Build demo application
        # working-directory: ./demo # This is handled by defaults now
        run: npm run build # Vite outputs to demo/dist by default relative to its root (demo/)
                          # So, the artifact path will be ./demo/dist from workspace root

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path is relative to the GITHUB_WORKSPACE
          path: ./demo/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 