name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - main # Or your primary branch name
    paths:
      - 'demo/**' # Only run if demo files change
      - '.github/workflows/deploy-demo.yml' # Or the name of this workflow file
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy Demo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: ./demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a version compatible with your project
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            demo/package-lock.json
            - name: Install root dependencies
        
      - run: npm ci
        name: "Install root dependencies"
        working-directory: . # Run this at the repository root

      - name: Install demo dependencies
        working-directory: ./demo
        run: npm i --force # Reverted to npm ci, relies on a correct package-lock.json

      - name: Build demo application
        working-directory: ./demo
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./demo/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 